---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: inclusion-crac
spec:
  template:
    spec:
      containers:
      - image: $REGISTRY_HOST/inclusion-crac
        name: user-container
        securityContext:
          capabilities:
            add:
              - CHECKPOINT_RESTORE
              - SYS_PTRACE
          runAsUser: 0
          allowPrivilegeEscalation: false
